### ISSUE TITLE
History data seems inaccurate

### ISSUE THREAD

**Issue by ColinRobbins** [petergridge/openweathermaphistory#10]
I have noticed a potential inaccuracy in the rainfactor history data.

Using the rain sensor `sensor.openweathermap_rain` it shows I had rain 17 hours ago (shown via the home assistant history).
However the sensor `sensor.rainfactor` shows `day_0_rain` as zero.   (It did show rain a few hours previously).
Other days show rain.

I am wondering it if is a timezone calculation issue?

**Comment by ColinRobbins** [comment]
Closing - May be an issue my end.

**Comment by petergridge** [comment]
Hi Colin, I have noticed that the history feed from OpenWeather can be out of sync for a while or just plain wrong. I believe they are no longer provisioning the history capability with new accounts so it may just be a matter of time before I have to find a new way to get this data.
