### ISSUE TITLE
HASS integration

### ISSUE THREAD

**Issue by Jozef73** [petergridge/openweathermaphistory#13]
Hi there,

I've got this message after integration to HASS:

This entity is no longer being provided by the openweathermaphistory integration. If the entity is no longer in use, delete it in settings.

any advice?

thank you
Jozef

**Comment by petergridge** [comment]
Hi @Jozef73,

I have not seen this issue before, are you upgrading from a previous version or is this the first time that you have installed this?

if you are upgrading, try deleting the older version and restarting hass before reinstalling.

If this is the first time, are there any other error messages in the logs?

Cheers

**Comment by Jozef73** [comment]
Hi Peter this was fisrt time installation.
My HASS is quite new and all is updated.
Nevermind, I manage to get rain history data in NodeRed using API and posting to HASS via Mqtt.

thank you
regards
jozef

**Comment by greenfun2** [comment]
I'm having the same issue.   I just installed HACS for the first time today.  I'm running Home Assistant OS v9.5.
I'm getting this in my log:  

```
Logger: homeassistant.components.sensor
Source: custom_components/openweathermaphistory/weatherhistory.py:53
Integration: Sensor (documentation, issues)
First occurred: 11:14:34 AM (2 occurrences)
Last logged: 11:14:34 AM

Error adding entities for domain sensor with platform openweathermaphistory
Error while setting up openweathermaphistory platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/openweathermaphistory/sensor.py", line 184, in async_added_to_hass
    await self._weatherhist.async_update()
  File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 53, in async_update
    current = data["current"]
KeyError: 'current'
```

**Comment by petergridge** [comment]
hi @greenfun2,

I get this error if the API key is not set correctly. Can you check you have copied the api_key from your openweathermap registration accurately.

I will look to add better error handling for this in a future release.

Cheers

**Comment by dennisleussink** [comment]
I got the exact same error after installing via HACS.

Key is valid and active. What can be the issue?

**Comment by petergridge** [comment]
Can you put the following url in your browser and send me the result. You will need to add in your api_key. The dt=will be good for 4 days or so other wise you can replace this with the current unix time. This is the call that the program makes to get the data processed.

https://api.openweathermap.org/data/2.5/onecall/timemachine?lat=43.5226349&lon=144.158075&dt=1681869009&units=metric&appid=api_key

**Comment by petergridge** [comment]
I have added V1.1.2 as a pre release version, this will give better error handling of API call failures. You will need to set the 'show beta versions' options

**Comment by greenfun2** [comment]
> Can you put the following url in your browser and send me the result. You will need to add in your api_key. The dt=will be good for 4 days or so other wise you can replace this with the current unix time. This is the call that the program makes to get the data processed.
> 
> https://api.openweathermap.org/data/2.5/onecall/timemachine?lat=43.5226349&lon=144.158075&dt=1681869009&units=metric&appid=api_key

```
{"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}
```

I got the same result with both my API keys, copied right from their website.

**Comment by dennisleussink** [comment]
Same error for me as well.

**Comment by petergridge** [comment]
The integration relies on version 2.5 of the API, I have been looking at the OWM site and can't see how to subscribe for that version now.

A new version that supports v3 for the same outcome is under development now and will hopefully be available soon.

**Comment by greenfun2** [comment]
Thank you!

**Comment by petergridge** [comment]
I have added V1.2.0 as a pre release version, this support API V3. This version is not backward compatible with V2.5.

Be aware this is still an early beta, it is still fundamentally the same as the previous version but has not been up and running very long. If you see any errors in your log please let me know.

You will need to set the 'show beta versions' options

**Comment by maxoss** [comment]
Installed 1.2 no issues so far. I already had a subscription for one call 3.0. Set openweathermaps updates to onecall_hourly

**Comment by greenfun2** [comment]
Works for me, too.
