### ISSUE TITLE
Upgrade from v1.0

### ISSUE THREAD

**Issue by loopy321** [petergridge/openweathermaphistory#19]
Hello,
Thanks for the great work on this!

I just updated to v2.0 from v1.0 and am trying to figure out how to get the same `sensor.rainfactor` back with the attributes I was using in my automations.  I see the new Modify Sensor and Jinja2 template, but not sure how to best replicate the old sensor.

Any tips for this migration?  
Thanks!

**Comment by petergridge** [comment]
Hi @loopy321,


for the version 1 equivalent:
```
{{ 
  [(10 
  - day0rain 
  - day1rain*0.5
  - day2rain*0.25
  - day3rain*0.12
  - day4rain*0.06)/10
  ,0]|max
}}
```
I am trying this one that takes into account forecast rain
```
{{ 
  [(10 
  - day0rain 
  - day1rain*0.5
  - day2rain*0.25
  - forecast1rain*forecast1pop*0.5
  - forecast2rain*forecast2pop*0.25)/10
  ,0]|max
}}
```
add the sensor like this
![image](https://github.com/petergridge/openweathermaphistory/assets/40281772/b93e8104-a828-4160-a32a-a80927625a21)

You can add both sensors just give them different names

Cheers
Pete

**Comment by loopy321** [comment]
Thanks for the reply!!  

I just realized that I am also getting the following error:
```
Logger: homeassistant.components.sensor
Source: custom_components/openweathermaphistory/weatherhistory.py:320
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 7:27:05 PM (1 occurrences)
Last logged: 7:27:05 PM

Error while setting up openweathermaphistory platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/openweathermaphistory/sensor.py", line 70, in async_setup_entry
    await weather.async_update()
  File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 283, in async_update
    historydata = await self.get_historydata(historydata)
  File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 320, in get_historydata
    self._cumulative_rain += hourdata.get("rain")
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```
Maybe I jest need to wait some time for a new API pull?  Or does this look like something else?

**Comment by petergridge** [comment]
No this is a bug, I think I have isolated it and will issue an update, I am not experiencing this myself and you are first to report it. So I am not sure what the underlying cause is.

You should also have a warning message "OpenWeatherMap history call failed" can you check your logs for this for me.

**Comment by loopy321** [comment]
Yes, see below:
```
2023-06-07 19:31:20.251 WARNING (MainThread) [custom_components.openweathermaphistory.weatherhistory] OpenWeatherMap history call failed
2023-06-07 19:31:20.257 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up openweathermaphistory platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/openweathermaphistory/sensor.py", line 70, in async_setup_entry
await weather.async_update()
File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 283, in async_update
historydata = await self.get_historydata(historydata)
File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 320, in get_historydata
self._cumulative_rain += hourdata.get("rain")
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

**Comment by petergridge** [comment]
Great, that means I have am on the right track. What should happen is that you get the warning when the API call fails (no error) and it just retries later. I have two lines out of order.

I will have a beta version up soon

**Comment by petergridge** [comment]
V2.0.5 Beta released. In HACS ensure you have the show beta option checked.

Let me know if this should resolve your issue, let me know how it goes.

Regards
Pete

**Comment by jeffjensen** [comment]
Thank you, mine had the same issue and now works with v2.0.5.

**Comment by jeffjensen** [comment]
Well, I commented too soon.  I saw the value for awhile but now it is "unavailable" again.  
This is the log messages:
```
OpenWeatherMap history call failed

Unexpected error fetching openweathermaphistory data: min() arg is an empty sequence
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/openweathermaphistory/sensor.py", line 94, in _async_update_data
    await self._weather.async_update()
  File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 267, in async_update
    historydata = await self.async_backload(historydata)
  File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 337, in async_backload
    startdp = min(data) - 3600
ValueError: min() arg is an empty sequence
```

**Comment by petergridge** [comment]
Hi Jeff,

Thanks for this info, it is strange that the API call is failing consistently for you. Can I confirm that you have signed up for the latest version of the API?

From a testing point of view it is good to see the behaviour when the API is failing, it is hard to emulate real world failures.

I have added a fix but we could find some more gremlins down stream a new beta will be up shortly

**Comment by petergridge** [comment]
V2.0.6 is up hopefully this fixes the failures, I am concerned with the API calls not being successful though. The program may not error out but not much use if the API calls are failing.

Can you try to run this in your browser, you will need to replace XXXXXXXXX with your API key.

https://api.openweathermap.org/data/3.0/onecall?lat=-33.8583713&lon=151.2134596&exclude=minutely,alerts&appid=XXXXXXXXX&units=metric 

You should get weather data or error message, I am interested to know what messages you get back.

**Comment by loopy321** [comment]
I updated my API subscription back in Feb, but did not sign up for the pay-service OneCall API 3.0 - is this necessary?  The OWH v1.0 worked yesterday with my API key.
I tried the above link and received the following

```
{
  "cod": 401,
  "message": "Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info."
}
```

**Comment by petergridge** [comment]
Hi, the new version needs a new subscription, it is the same key. 

To generate API key go to https://openweathermap.org/api and subscribe to 'One Call API 3.0'. You need to enter billing info to get 1,000 free calls per day. Configure your account to never go over the free limit here: https://home.openweathermap.org/subscriptions

**Comment by jeffjensen** [comment]
Thanks for continuing to investigate and fix!

> Can I confirm that you have signed up for the latest version of the API?

Yep, says "V2.0.6" on the openweathermaphistory integration page.  Just upgraded again.

> Can you try to run this in your browser, you will need to replace XXXXXXXXX with your API key.
> You should get weather data or error message, I am interested to know what messages you get back.

Aha! Me too:
{"cod":401, "message": "Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info."}

> Hi, the new version needs a new subscription, but still uses the same key.

Apologies, I did not realize that.  Will do...

**Comment by petergridge** [comment]
I have found a better way to confirm if the API key is valid for One Call 3.0, I am testing it at the moment. 

I am glad that you had the issue as it helps me refine this part of the code. :)

**Comment by jeffjensen** [comment]
With the One Call 3.0 setup, the https://api.openweathermap.org/data/3.0/onecall?lat=-33.8583713&lon=151.2134596&exclude=minutely,alerts&appid=XXXXXXXXX&units=metric URL now works.

However, the rainfactor is still unavailable and the log shows a new problem: moved from min() error to max() error, lol:
```
Unexpected error fetching openweathermaphistory data: max() arg is an empty sequence
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/openweathermaphistory/sensor.py", line 94, in _async_update_data
    await self._weather.async_update()
  File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 267, in async_update
    historydata = await self.async_backload(historydata)
  File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 347, in async_backload
    targetdp = max(data) - (self._initdays*3600*24)
ValueError: max() arg is an empty sequence
```

**Comment by petergridge** [comment]
This could be a hangover from the bad API.

Can you try deleting the two .pickle files in the config directory. I think that will help. 

I will put a new version tomorrow that should guard against this. It is getting late here.

**Comment by petergridge** [comment]
Sorry, Please install the new version it has better exception handling for the API calls, and may help debug this.

**Comment by petergridge** [comment]
OK 2.0.7 is out hopefully sort this out.

Fingers crossed.

**Comment by loopy321** [comment]
Looks like it might be working after I entered CC info for the upgrade.
But got this error initially:
`2023-06-08 17:22:55.623 ERROR (MainThread) [custom_components.openweathermaphistory.weatherhistory] OpenWeatherMap call failed code: 401: Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info.`
However, I am now seeing what looks correct:
![2023-06-08 17_30_47-Settings – Home Assistant](https://github.com/petergridge/openweathermaphistory/assets/1026345/5584b116-33b3-4f5e-86cf-61cddcee6742)

**Comment by petergridge** [comment]
Hi, I have added a new service to the latest version. Choose any entity from the list.
![image](https://github.com/petergridge/openweathermaphistory/assets/40281772/6ee174d1-5694-4f04-89fa-40a08f0bc40e)
Try running this it will use your setting and execute the API to double check if there are any issues. Just check to log for the outcome.

**Comment by petergridge** [comment]
Hi Can you download the latest version, it fixes an issue with the API call feature

**Comment by jeffjensen** [comment]
2.0.7 has run successfully all day, so seems fixed!  Thank you.

Noted this error message with 2.0.7, not sure if existed prior:
```
ERROR (MainThread) [homeassistant.components.sensor] The openweathermaphistory platform for the sensor integration does not support platform setup. Please remove it from your config.
```

**Comment by petergridge** [comment]
A couple of checks:
1. Can you see min or max temperature values? You can just add a new sensor {{ day0max }} to check
2. Have you removed the config for the last version from your YAML, I think that is the error you are seeing

FYI 2.0.7 has my API key hard coded in the test service, I should not work late at night, so you need to update to the V2.0.8. I am removing that api key.

I am also adding a new service to the next release that allows you to list all the available variables and their current values, this will help debug in the future or simply see what variables you have to build your sensors with.

**Comment by jeffjensen** [comment]
> 1. Can you see min or max temperature values? You can just add a new sensor {{ day0max }} to check

developer-tools/state for my sensor.rainfactor show:
```
attribution: Data provided by OpenWeatherMap
icon: mdi:weather-pouring
friendly_name: rainfactor
day0rain: 0
day1rain: 0
day2rain: 0
day3rain: 0
day4rain: 0
day0max: 26.02
day1max: 26.55
day2max: 28.22
day3max: 29.13
day4max: 31.25
day0min: 14.66
day1min: 18.11
day2min: 19.13
day3min: 19.04
day4min: 19.56
```

> 2. Have you removed the config for the last version from your YAML, I think that is the error you are seeing

Ah thanks, that was it!  Forgot that was there...

> FYI 2.0.7 has my API key hard coded in the test service, I should not work late at night, so you need to update to the V2.0.8. I am removing that api key.

lol!! Already upgraded.

> I am also adding a new service to the next release that allows you to list all the available variables and their current values, this will help debug in the future or simply see what variables you have to build your sensors with.

Sounds great!  Very useful.

**Comment by petergridge** [comment]
Excellent! I will close this issue.

**Comment by loopy321** [comment]
Got mine working too.  Thanks!  Also, should I open a separate issue about the units?  
It is set to "in", but looks like still mm:
![2023-06-08 19_44_04-Settings – Home Assistant](https://github.com/petergridge/openweathermaphistory/assets/1026345/520fee90-111d-4533-807c-4446c6fead54)
