### ISSUE TITLE
Units setting?

### ISSUE THREAD

**Issue by loopy321** [petergridge/openweathermaphistory#20]
Again, thanks for the work on this. In an effort to help troubleshoot, I have noticed that the units are not correct.  See below with sensor set to "in" but apparently reporting "mm" (this is on v.2.08):
![2023-06-08 19_55_18-Developer Tools – Home Assistant](https://github.com/petergridge/openweathermaphistory/assets/1026345/2e80a5f0-c0e1-4d83-9fb3-7015f4886e79)

**Comment by petergridge** [comment]
The attributes of the sensor are metric. But if you create a new sensor {{ day2rain }} for example and set the type 'precipitation' it will present as imperial on the sensor.

I am assuming you have the rainfactor calculation it probably should not be set  to the device class of precipitation as it is only a factor, % to apply.

**Comment by loopy321** [comment]
Thanks for the suggestion.  I tried that, but the "type" does not set - I tried re-editing it and saving as precipitation, but does not work (keeps making it blank):
![2023-06-08 20_08_53-Settings – Home Assistant](https://github.com/petergridge/openweathermaphistory/assets/1026345/52bef20c-1d04-4758-ac8d-e378b6f56500)

**Comment by petergridge** [comment]
Try adding a new sensor, rather than editing the existing one, I will check what is happening on the modify.

**Comment by loopy321** [comment]
As a side note - the "add ons" disappeared from my "settings" home assistant menu with the most recent v2.08.  Not sure why.

**Comment by petergridge** [comment]
I haven't experienced that. I just updated two devices rpi's to the version with no impact on the settings. Maybe a restart is required?

**Comment by josephny** [comment]
I am unable to get results to show in imperial either.

**Comment by petergridge** [comment]
Hi @josephny ,

I hope this helps:

All data is captured in metric measurements.

To see the information in your local unit of measure:
- Ensure you select the appropriate 'Type of sensor'. This will allow HA to display information in the unit of measure defined for your instance.
- If you change the type of sensor you will see warnings in the log as the unit of measure will be inconsistent, go to the developers tools/statistics page to fix the issue.
```
WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.current_temp (°C) cannot be converted ...
Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
```
- If your instance is defined for the metric measurement system and you still wish to see imperial you can change the unit of measure (°C to °F) for each sensor in the sensor settings.

**Note**
Unit of measure is not applied to attributes, it is applied only to the sensor state. Attribute values are supplied as metric values. HA recommends that rapidly changing attributes are not used on sensors as this impact the history capture, instead create multiple sensors.

**Comment by petergridge** [comment]
Hi, I'm after opinions/requests for the next release of this. No promises on a timeline though. This is just a requirements, wish list exercise at the moment.

This is what I am proposing:
1. Allow the selection of, rain, snow, min, max... to automatically create sensors for the number of days configured. This will limit the configuration required to only the complex but could blow out the number of sensors exposed on your system. This will also resolve the unit of measure being metric in the attributes.
2. Modify the custom card to display based on the created sensors - I haven't thought the UI through yet so this is a little aspirational as I am not a good UI developer. 

Are there any request that I can add to the backlog, happy to consider, but can't promise on delivery 😄
