### ISSUE TITLE
Sensor in the list but no related entity in HA

### ISSUE THREAD

**Issue by tanker11** [petergridge/openweathermaphistory#27]
Hello,

I have V2.0.10 version.
There was no reaction on earlier configured entities so deleted all, and re-installed the integration.
Now if I add a sensor, it is not listed as entity, but in the list of modifiable sensors:

<img width="218" alt="image" src="https://github.com/petergridge/openweathermaphistory/assets/32165691/b8cb1d98-2fe6-4e29-ba44-843775bed78b">

What could be wrong?

**Comment by petergridge** [comment]
Hi @tanker11,

Just letting you know I am looking into this issue, I can't recreate it, can you check the logs to see if there are any errors appearing that may help me identify the problem.

Cheers
Pete

**Comment by petergridge** [comment]
I have just released 2.0.11 that fixes a bug in the list variables service call.

Can you run this and check your log (best to download the log) to verify that you are getting values for the vaiable.

Cheers
Pete

**Comment by tanker11** [comment]
Just tried, and exactly the same: I have a defined sensor, but not listed,
only if I enter into the  'Modify' menu item.

Error in the log:
EOFError: Ran out of input
2024-01-30 10:21:26.191 ERROR (MainThread)
[homeassistant.components.sensor] Error while setting up
openweathermaphistory platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",
line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/openweathermaphistory/sensor.py", line
71, in async_setup_entry
    await weather.async_update()
  File "/config/custom_components/openweathermaphistory/weatherhistory.py",
line 253, in async_update
    dailycalls = self.get_stored_data('owm_api_count').get('dailycalls',{})
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openweathermaphistory/weatherhistory.py",
line 71, in get_stored_data
    content = pickle.load(myfile)


NOTE: I have checked on
https://home.openweathermap.org/statistics/onecall_30 my usega data, and it
say 1 call was only made.


Peter ***@***.***> ezt írta (időpont: 2024. jan. 27., Szo,
23:22):

**Comment by petergridge** [comment]
Can you try to run the call below. replace XXXXX with your API key.

https://api.openweathermap.org/data/3.0/onecall?lat=-33.8583713&lon=151.2134596&exclude=minutely,alerts&appid=XXXXXXXXX&units=metric

This will confirm that the api call is working and your registration is for v3

**Comment by tanker11** [comment]
Tried and it works. I got a valid JSON response:

{"lat":-33.8584,"lon":151.2135,"timezone":"Australia/Sydney","timezone_offset":39600,"current":{"dt":1706610845,"sunrise":1706555623,"sunset":1706605357,"temp":23.33,.....


Peter ***@***.***> ezt írta (időpont: 2024. jan. 30., K,
11:05):

**Comment by petergridge** [comment]
Can you check in your config directory and confirm that there are two .pickle files

one for the instance e.g. home.pickle and owm_api_count.pickle.

Can you delete both of these and restart, I am clutching at straws but it appears from the error log that the owm_api_count.pickle is there but could be corrupted.

**Comment by tanker11** [comment]
I was a good bet!
I located the .pickle files and owm_api_count.pickle had 0 length.
After deleting them and restart everything goes well, I can add and modify
sensors as before. Thanks!

Peter ***@***.***> ezt írta (időpont: 2024. jan. 31., Sze,
2:42):
