### ISSUE TITLE
 Config flow could not be loaded: {"message":"Invalid handler specified"} 

### ISSUE THREAD

**Issue by roeger** [petergridge/openweathermaphistory#28]
I installed v2.0.11 from HACS on a  home assistant core 2024.2.2 and restarted home assistant.
Afterwards I tried to add the integration, and got the error:

`Config flow could not be loaded: {"message":"Invalid handler specified"}`

The log file says `Error occurred loading flow for integration openweathermaphistory: No module named 'pyowm'`.

After manually installing the package in my home assistant python environment, the error disappeared.

**Comment by petergridge** [comment]
Hi,
Thanks for letting me know, I have updated the dependencies in the manifest.json to include pyowm, this should notify HA to install the library.
