### ISSUE TITLE
HA crashed if updated to 2.0.12 from 2.0.11

### ISSUE THREAD

**Issue by MarQua** [petergridge/openweathermaphistory#29]
![error_ha](https://github.com/petergridge/openweathermaphistory/assets/17424611/07c8d20e-2532-4361-890b-c6166d8f5c4f)
Hi,
I get the error as in the uploaded image.
If I try to update, HA consequntly crashes.
![info_ha](https://github.com/petergridge/openweathermaphistory/assets/17424611/2b3d163f-e08e-45f7-9691-1e96b966ec7c)

**Comment by FrancoLoco** [comment]
Similar problem here.. I just removed the custom component for now... it happened 2 times to me today before I realised who was the culprit

2024-02-21 14:10:00.738 ERROR (MainThread) [homeassistant.loader] Unable to resolve dependencies for openweathermaphistory:  we are unable to resolve (sub)dependency pyowm
2024-02-21 14:10:00.743 ERROR (MainThread) [root] Uncaught exception
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 221, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/runner.py", line 188, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in setup_and_run_hass
    hass = await bootstrap.async_setup_hass(runtime_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 203, in async_setup_hass
    await async_from_config_dict(config_dict, hass) is not None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 351, in async_from_config_dict
    await _async_set_up_integrations(hass, config)
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 658, in _async_set_up_integrations
    for dep in itg.all_dependencies:
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 776, in all_dependencies
    raise RuntimeError("Dependencies not resolved!")
RuntimeError: Dependencies not resolved!

**Comment by petergridge** [comment]
Hi,

Sorry about that, I added the to the dependency instead of the requirement and did not test properly. V2.0.13 is released now.

**Comment by FrancoLoco** [comment]
I made a few prayers and updated to the new version to try the fix and can confirm it works. Thanks for fixing so quickly.

**Comment by jeffjensen** [comment]
Anyone mind helping with how to recover from this please?  I'm ssh'd in but cannot find the install location or how to upgrade this from CLI.  My google-fu failing me!

**Comment by petergridge** [comment]
Hi, 

Components are install in the config/custom_components/ directory.

You can:
-  remove the entire openweathermaphistory folder and reinstall from HACS, or
-  edit the manifest.json file to remove the reference to 'pyowm' from the dependencies entry, the source of the problem.

Consider installing the SAMBA addon this makes it easier to get to the file system even when HA itself is not starting.

Cheers
Pete

**Comment by mikburnz** [comment]
Same for me. Cannot access the HA GUI. What can i do?? I have a backup just before this update. 
I have to do something in the shell. Please give me some codes and advices to bring my HA GUI back to access.

**Comment by petergridge** [comment]
Hi,

Do you have ssh access to you installation? you would have set it up when you configure HACS.

If so you should be able to access the file system and remove the custom component.
or with cli access you should be able to restart in safe mode. https://www.home-assistant.io/docs/tools/hass/ and uninstall the custom component.

The last resort would be to recover to your backup.

Sorry for the pain I've caused in that last update.

Cheers
Pete

**Comment by mikburnz** [comment]
i have ssh access. please describe me how i have to do step by step. 
This is really a pain. hundreds of hours work in this system. Never thought that a update can bring this situation.
Thank you.

**Comment by petergridge** [comment]
I think less attitude is in order, I have hundreds of hours putting this together for free I do not force you to use it or be the first to install an update. If you are not proficient in recovering I suggest you hold back on updates for a few weeks before taking on new versions. I did not exactly plan for this to happen. 

once in ssh:
ls     will list the directories
cd    will allow you to navigate to config and then custom_components
rmdir -r    will let you delete a directory and its contents.

So the steps are:
cd config
cd custom_components
rmdir -r openweathermaphistory

restart your server and then you can reinstall from HACS if you want.

**Comment by mikburnz** [comment]
thank you for your help of course. Last question. The easiest way for me is to connect monitor and keyboard. I'm then already in the HA CLI or do i have to do something?

are the steps shown above the the same?

need this possibility if ssh is without success (another problem)

**Comment by petergridge** [comment]
I'm not sure I have never connected a screen to my device. once you are logged on through ssh, you should have access to the files system. just navigate to the custom component directory and delete openweathermaphistory.

If you use ha cli try the backup option to restore from your backup

**Comment by MarQua** [comment]
I confirm that the new version 2.0.13 fixed the issue. Thanks for the quick solution.
