### ISSUE TITLE
Openweathermap History Not in Integration List

### ISSUE THREAD

**Issue by asmi242** [petergridge/openweathermaphistory#30]
I've downloaded this repository in HACS (tried v2.0.13 and 'main'), but when I try to install with the config workflow it does not appear on the list of integrations. I've checked the custom components folder and it has been successfully added there, with the most up to date manifest from this repository.

![image](https://github.com/petergridge/openweathermaphistory/assets/89297509/fb2d5b37-5a5a-4e1e-b8b5-afe0b73a1f3a)

**Comment by petergridge** [comment]
Hi,  use owm history, my shorthand has slipped into the naming, I will update in the next release

**Comment by asmi242** [comment]
> Hi, use owm history, my shorthand has slipped into the naming, I will update in the next release

Turns out it was something to do with my HA version. Updated it and the display name was corrected and it works fine now. Thanks.
