### ISSUE TITLE
get_forecast will be deprecated

### ISSUE THREAD

**Issue by tgrosz** [petergridge/openweathermaphistory#33]
I get a warning in HA that get_forecast will be deprecated and removed in June. The new get_forecasts service should be used.

**Comment by petergridge** [comment]
Hi @tgrosz,

Can you send me the log details, I am not seeing this issue with the versions of the app/HA that I am running.

Cheers
Pete

**Comment by tgrosz** [comment]
Hmmm, I was pretty sure this message belongs to OWM History as I have no other components for weather. But I have a weather card - I'll keep you updated. Thanks
