### ISSUE TITLE
OpenWeatherMap API excessive request amount

### ISSUE THREAD

**Issue by myreczek** [petergridge/openweathermaphistory#34]
After I set up the integration, add single sensor for `{{current_temp}}` the log shows:

`2024-04-30 08:20:53.679 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openweathermaphistory is taking over 10 seconds.`

I see excessive amount of requests to OWM API resulting in blocked access, e-mail from OWM stating:

> We have noticed that your account is currently using [One Call API 3.0](https://openweathermap.org/api/one-call-3) quite intensively and exceed your account limit of 999 API calls per day.

I have to disable the integration and restart HA else the requests won't stop.

HA version 2024.4.4.

**Comment by petergridge** [comment]
hi @myreczek,

Can you provide a copy of your API configuration just the two highlighted:
![image](https://github.com/petergridge/openweathermaphistory/assets/40281772/4a90dc6b-755f-443b-8d24-46ce3f88436d).

Have you defined more than one history integration configured?

The program can be a bit slow to load the first time as it is starting the backload of history data. I have it on my list of tasks to try and move this load to after HA starting has completed, but I am still working on a viable solution.

If your Max API calls per day is high and you are backloading many days of data this could use your daily allocation of API calls. The backload of data only uses 24 calls per day so hitting a thousand calls is unusual.

There are two sensors you can configure: {{remaining_backlog}}, number of days remaing to load, and {{daily_count}} how many API calls have been made, these provide an insight into the number of calls being made and still to be made to catch up.

**Comment by petergridge** [comment]
I Understand, lets check a few more things, do you have two '.pickle' files in the configuration directory? These are the files that persist the information captured and stores the count of API calls made to OWM. If these are being prevented from being written this could cause the program to keep sending API calls. 

What style of Home Assistant installation are you running and what hardware?

If you do configure the component again it is important that you also add the two sensors that show how many calls have been made so you can monitor the usage.
