### ISSUE TITLE
A variable used is undefined, check the log for details

### ISSUE THREAD

**Issue by boelle** [petergridge/openweathermaphistory#40]
i created a sensor for the last 24 hours no problem

then i tried to create another one for the last 30 days and got this:

![image](https://github.com/petergridge/openweathermaphistory/assets/3832239/6d210efd-7666-443f-936d-c14388d23b81)

sure its me thats doing something wrong but cant figure what

lastest non beta of the integration and HA fully updated

EDIT... anything above 9 days makes it fail

EDIT2... of course, you cant go longer than the days it buffers data... big DOOOOH here, but the graphs contain negative data

![image](https://github.com/petergridge/openweathermaphistory/assets/3832239/163924d3-03ce-45a1-8362-556b19dc81a2)

prob because it has not fetched any data yet?

**Comment by petergridge** [comment]
You can vary how many sensor variables are provided by setting the days to keep, days to backload options. If you want 30 days of history I would recommend still setting the days to backload to manage the API calls used and wait for the remaining days to come in as the days pass.
![image](https://github.com/petergridge/openweathermaphistory/assets/40281772/a06910fa-c1a7-41d8-be21-b509d2391b1f)

Hi, you can see the sensor options available by this service
![image](https://github.com/petergridge/openweathermaphistory/assets/40281772/b8a65540-6762-4ecb-9bf8-4d357c26e732)
Just set the entity to one of the sensors you have created, I always create the backload sensor.
 you should see something like this in your log file

![image](https://github.com/petergridge/openweathermaphistory/assets/40281772/7f6c04f9-f503-4cc2-84c6-b9fe7a31dc44)

It should automatically create an option for the full set of values up to the days to backload limit. however on testing, this is not the behaviour. I will revisit this for the next release.

**Comment by boelle** [comment]
prob me that is a bit impatient

![image](https://github.com/petergridge/openweathermaphistory/assets/3832239/2afe545e-c58b-480c-a6a9-e720cc2f39c1)


but rain for the last 30 days says 0 but we have had more than 15 mm rain during the last week

![image](https://github.com/petergridge/openweathermaphistory/assets/3832239/d566177b-2513-40f9-b5fa-f13d64fc8a35)

**Comment by boelle** [comment]
hmm more odd

![image](https://github.com/petergridge/openweathermaphistory/assets/3832239/ea0dadc7-3b2d-45ce-852d-fddd00bfafc1)

**Comment by petergridge** [comment]
If you set ballad to two, it will load 2 days of data and then it will take 28 days to be the remaining data before it starts removing days of history.

**Comment by boelle** [comment]
> If you set ballad to two, it will load 2 days of data and then it will take 28 days to be the remaining data before it starts removing days of history.

so it will load 2 days the first day, the next day another 2?

**Comment by petergridge** [comment]
No,  2 days,  and then each day just that one day. Until it reaches the maximum of 30 days and then it will remove data to maintain only 30 days of data.  If you really need 30 days and you only have one integration it is only 720 calls so it should not impact your free api limitSent from my Galaxy
-------- Original message --------From: Bo Herrmannsen ***@***.***> Date: 1/7/24  6:56 pm  (GMT+10:00) To: petergridge/openweathermaphistory ***@***.***> Cc: Peter ***@***.***>, Comment ***@***.***> Subject: Re: [petergridge/openweathermaphistory] A variable used is undefined, check the log for details (Issue #40) 

If you set ballad to two, it will load 2 days of data and then it will take 28 days to be the remaining data before it starts removing days of history.

so it will load 2 days the first day, the next day another 2?

**Comment by boelle** [comment]
last 24 hours is updated now, but should the last 30 days one not have the same amount of rain if the 2 sensors are created at the same time?

**Comment by petergridge** [comment]
day30rain is the rain that fell on that day,  not the cumulative total of the last 30 days.

**Comment by petergridge** [comment]
Have a look at the utility meter integration. That is an option to use with the cumulative rain

**Comment by petergridge** [comment]
Happy to consider additional features if you have some specific requirement

**Comment by boelle** [comment]
i will let you know if i get any "crazy" ideas bu ti think i can close this one for now and file it under me not understanding things correctly the first way round

**Comment by boelle** [comment]
the only thing i can think of are "integrated" options for rain during the last X days or hours

**Comment by boelle** [comment]
i got things working for the last 24 hours and monthly rain

but you said to use ultility meter, i read the documentaion but its not clear how it works

would this work to get me rain for the last hour? will test it but we have not had any rain today so if its wrong let me know

utility_meter:
  energy:
    source: sensor.rain_during_the_last_24_hours
    cycle: hourly

**Comment by petergridge** [comment]
The data is in 24 hour time slots, not date based, but data for the preceeding 24hrs.

So the utility meter should add a days point once per day to show long term data. 

You could get hourly rainfall from your weather integration sensors.

**Comment by boelle** [comment]
well openweathermap have a rain each hour mumber

https://community.home-assistant.io/t/rain-in-the-last-days/463134/8

but that one updates each 10 minutes... and i have not figured if that is just an ever climbing number or if it shows the last rolling window hour

**Comment by boelle** [comment]
found some help here: https://community.home-assistant.io/t/rain-sensor-tracking/602558/15?u=boelle

so yeah the openweathermap integration is not perfect
