### ISSUE TITLE
New error in log

### ISSUE THREAD

**Issue by finity69x2** [petergridge/openweathermaphistory#43]
I got an error after restarting HA;

![image](https://github.com/user-attachments/assets/ea6c178a-ad00-40fa-b91e-8913f5c00f52)

```
2024-09-18 16:11:00.309 ERROR (MainThread) [homeassistant.config_entries] Error migrating entry Home for openweathermaphistory
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 943, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openweathermaphistory/__init__.py", line 73, in async_migrate_entry
    file = os.path.join(hass.config.path(), cv.slugify(name)  + '.pickle')
                                            ^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 612, in slugify
    raise vol.Invalid("Slug should not be None")
voluptuous.error.Invalid: Slug should not be None
```

I tried restarting HA again with no change.

I verified the integration config and it seems the same as it has previously that was working so I'm not sure how to proceed.

any help you can give would be appreciated.

**Comment by petergridge** [comment]
Hi, I think I know what is happening, it looks like you have never edited the configuration since it was created and I missed that wrinkle in my code. 

If you want to fix this quickly just delete and recreate the entry, no need to reinstall. But check your config directory and remove the '.pickle' files. 

I will have a new release out shortly (a few hours) that should address the problem.

**Comment by petergridge** [comment]
Ok that was quicker than expected, V2024.09.01 release with a change, I can't test the issue so please let me know how you go.

cheers
Pete

**Comment by finity69x2** [comment]
thanks for the quick response.

I'll wait till the update posts on HACS and test it and I'll definitely let you know.

**Comment by finity69x2** [comment]
Well that's interesting...

I haven't updated yet since the update hasn't shown up in HACS but I needed to restart a couple of times for various other reasons and suddenly the error is gone.

I dunno.

If it comes back I'll let you know. 

Hopefully it won't after I get the update.

**Comment by petergridge** [comment]
Thanks, I will close the ticket for now.
