### ISSUE TITLE
entities not updating and problems editing sensors

### ISSUE THREAD

**Issue by Saschman** [petergridge/openweathermaphistory#44]
Hi,
i currently have HASS running in the following versions:
Core 2024.9.2
Supervisor 2024.09.1
Operating System 13.1
Frontend 20240909.1

I setup open weather map history yesterday.

I have 4 Sensors:
-currentTemp {{current_temp}}
-rain forecast 24h {{forecast0pop}}
-rain history 24h {{day0rain}}
-current rain {{current_rain}}

The currentTemp sensor updates itself every hour. The other 3 sensors don't seem to update at all. All of them were updated over 12 hours ago when I initially set everything up.

Another anomaly I found was when I try to modify existing sensors the wrong template is displayed. For example when I modify the sensor "current Temp" it shows "{{day0rain}}" in the Jinja2 Template input field.

can you help?

BR

**Comment by petergridge** [comment]
Hi, I have a fix for the indexing issue causing the update being out of sync will get that out ASAP.

Can you verify that you are getting data relating to the 3 problem sensors. The data is in the .storage directory in a file names OWMH_{name} Name is the name you gave the implementation. The numeric value on each record is the unix time for the collection.

The data comes in three section:
![image](https://github.com/user-attachments/assets/95a66c4d-c1f9-4fd6-ad6f-ba14ebbbb582)


```
{
  "version": 1,
  "minor_version": 1,
  "key": "OWMH_Home",
  "data": {
    "history": {
      "1728090000": {
        "rain": 0,
        "snow": 0,
        "temp": 26.25,
        "humidity": 36,
        "pressure": 1003
      },
      "1728093600": {
        "rain": 0,
        "snow": 0,
        "temp": 26.14,
        "humidity": 35,
        "pressure": 1003
      },
      "1728086400": {
        "rain": 0,
        "snow": 0,
        "temp": 25.97,
        "humidity": 43,
        "pressure": 1007
      },
      "1728082800": {
        "rain": 0.32,
        "snow": 0,
        "temp": 22.55,
        "humidity": 60,
        "pressure": 1004
      },
      "1728079200": {
        "rain": 0,
        "snow": 0,
        "temp": 22.58,
        "humidity": 64,
        "pressure": 1004
      },
      "1728075600": {
        "rain": 0,
        "snow": 0,
        "temp": 20.05,
        "humidity": 70,
        "pressure": 1003
      },
      "1728072000": {
        "rain": 0,
        "snow": 0,
        "temp": 17.12,
        "humidity": 75,
        "pressure": 1003
      },
      "1728068400": {
        "rain": 0,
        "snow": 0,
        "temp": 16.78,
        "humidity": 76,
        "pressure": 1003
      },
      "1728064800": {
        "rain": 0,
        "snow": 0,
        "temp": 16.24,
        "humidity": 79,
        "pressure": 1002
      },
      "1728061200": {
        "rain": 0,
        "snow": 0,
        "temp": 16.29,
        "humidity": 81,
        "pressure": 1004
      },
      "1728057600": {
        "rain": 0.75,
        "snow": 0,
        "temp": 16.87,
        "humidity": 79,
        "pressure": 1004
      },
      "1728054000": {
        "rain": 2.05,
        "snow": 0,
        "temp": 17.57,
        "humidity": 79,
        "pressure": 1005
      },
      "1728050400": {
        "rain": 0.13,
        "snow": 0,
        "temp": 17.41,
        "humidity": 81,
        "pressure": 1008
      },
      "1728046800": {
        "rain": 0,
        "snow": 0,
        "temp": 17.47,
        "humidity": 80,
        "pressure": 1006
      },
      "1728043200": {
        "rain": 0.49,
        "snow": 0,
        "temp": 17.57,
        "humidity": 83,
        "pressure": 1007
      },
      "1728039600": {
        "rain": 0,
        "snow": 0,
        "temp": 18.08,
        "humidity": 77,
        "pressure": 1008
      },
      "1728036000": {
        "rain": 0.56,
        "snow": 0,
        "temp": 18.58,
        "humidity": 77,
        "pressure": 1011
      },
      "1728032400": {
        "rain": 0,
        "snow": 0,
        "temp": 19.85,
        "humidity": 72,
        "pressure": 1008
      },
      "1728028800": {
        "rain": 0,
        "snow": 0,
        "temp": 20.79,
        "humidity": 67,
        "pressure": 1008
      },
      "1728025200": {
        "rain": 0,
        "snow": 0,
        "temp": 23.03,
        "humidity": 55,
        "pressure": 1008
      },
      "1728021600": {
        "rain": 0,
        "snow": 0,
        "temp": 24.1,
        "humidity": 50,
        "pressure": 1009
      },
      "1728018000": {
        "rain": 0,
        "snow": 0,
        "temp": 25.55,
        "humidity": 45,
        "pressure": 1010
      },
      "1728014400": {
        "rain": 0,
        "snow": 0,
        "temp": 25.77,
        "humidity": 45,
        "pressure": 1011
      },
      "1728010800": {
        "rain": 0,
        "snow": 0,
        "temp": 24.55,
        "humidity": 51,
        "pressure": 1012
      }
    },
    "current": {
      "rain": 0,
      "snow": 0,
      "temp": 26.64,
      "humidity": 34,
      "pressure": 1005
    },
    "dailyforecast": {
      "1728090000": {
        "max_temp": 26.95,
        "min_temp": 15.9,
        "pressure": 1005,
        "humidity": 30,
        "pop": 0.72,
        "rain": 1.06,
        "snow": 0
      },
      "1728176400": {
        "max_temp": 28.41,
        "min_temp": 13.83,
        "pressure": 1011,
        "humidity": 23,
        "pop": 0,
        "rain": 0,
        "snow": 0
      },
      "1728262800": {
        "max_temp": 31.23,
        "min_temp": 13.49,
        "pressure": 1015,
        "humidity": 22,
        "pop": 0,
        "rain": 0,
        "snow": 0
      },
      "1728349200": {
        "max_temp": 19.91,
        "min_temp": 11.89,
        "pressure": 1025,
        "humidity": 80,
        "pop": 0.78,
        "rain": 0.87,
        "snow": 0
      },
      "1728435600": {
        "max_temp": 16.91,
        "min_temp": 12.7,
        "pressure": 1028,
        "humidity": 48,
        "pop": 0.04,
        "rain": 0,
        "snow": 0
      },
      "1728522000": {
        "max_temp": 27.16,
        "min_temp": 13.26,
        "pressure": 1021,
        "humidity": 43,
        "pop": 0,
        "rain": 0,
        "snow": 0
      },
      "1728608400": {
        "max_temp": 20.8,
        "min_temp": 13.55,
        "pressure": 1021,
        "humidity": 30,
        "pop": 0.12,
        "rain": 0,
        "snow": 0
      },
      "1728694800": {
        "max_temp": 22.04,
        "min_temp": 10.53,
        "pressure": 1023,
        "humidity": 30,
        "pop": 0,
        "rain": 0,
        "snow": 0
      }
    },
    "dailycalls": {
      "time": 1728086400,
      "count": 26
    },
    "cumlative": {
      "cumulativerain": 0,
      "cumulativesnow": 0
    }
  }
}
```

**Comment by petergridge** [comment]
V2024.10.01 (Beta) released.

**Comment by Saschman** [comment]
Hi,
it looks like this:

{
  "version": 1,
  "minor_version": 1,
  "key": "OWMH_Home",
  "data": {
    "history": {
      "1728061200": {
        "rain": 0,
        "snow": 0,
        "temp": 12.23,
        "humidity": 92,
        "pressure": 1018
      },
      "1728064800": {
        "rain": 0,
        "snow": 0,
        "temp": 11.07,
        "humidity": 94,
        "pressure": 1018
      },
      "1728068400": {
        "rain": 0,
        "snow": 0,
        "temp": 10.56,
        "humidity": 93,
        "pressure": 1018
      },
      "1728054000": {
        "rain": 0,
        "snow": 0,
        "temp": 14.46,
        "humidity": 77,
        "pressure": 1015
      },
      "1728046800": {
        "rain": 0,
        "snow": 0,
        "temp": 14.5,
        "humidity": 78,
        "pressure": 1017
      },
      "1728043200": {
        "rain": 0,
        "snow": 0,
        "temp": 15,
        "humidity": 71,
        "pressure": 1017
      },


[...]


      },
      "1728554400": {
        "max_temp": 19.29,
        "min_temp": 10.13,
        "pressure": 986,
        "humidity": 64,
        "pop": 0.31,
        "rain": 0.64,
        "snow": 0
      },
      "1728640800": {
        "max_temp": 12.85,
        "min_temp": 6.75,
        "pressure": 1013,
        "humidity": 61,
        "pop": 0,
        "rain": 0,
        "snow": 0
      },
      "1728727200": {
        "max_temp": 13.73,
        "min_temp": 5.1,
        "pressure": 1025,
        "humidity": 60,
        "pop": 0,
        "rain": 0,
        "snow": 0
      },
      "1728813600": {
        "max_temp": 14.03,
        "min_temp": 6.35,
        "pressure": 1016,
        "humidity": 66,
        "pop": 1,
        "rain": 0.45,
        "snow": 0
      },
      "1728900000": {
        "max_temp": 12.37,
        "min_temp": 5.31,
        "pressure": 1025,
        "humidity": 59,
        "pop": 0,
        "rain": 0,
        "snow": 0
      },
      "1728986400": {
        "max_temp": 13.83,
        "min_temp": 5.99,
        "pressure": 1024,
        "humidity": 54,
        "pop": 0,
        "rain": 0,
        "snow": 0
      }
    },
    "dailycalls": {
      "time": 1728338400,
      "count": 33
    },
    "cumlative": {
      "cumulativerain": 0,
      "cumulativesnow": 0
    }
  }
}

**Comment by Saschman** [comment]
Can confirm, that the new beta fixes the indexing problem.

**Comment by petergridge** [comment]
Can you run this action:
![image](https://github.com/user-attachments/assets/6d02935b-e829-40e1-9a26-b57ef8dbc2ac)
The results will be in the Log file. this will list the value of all the available sensors

**Comment by petergridge** [comment]
Just a note: rain forecast 24h {{forecast0pop}} is the probability of precipitation.

**Comment by Saschman** [comment]
The interface gives an error:
Die Aktion openweathermaphistory.list_vars konnte nicht ausgeführt werden. not a valid value for dictionary value @ data['entity_id']. Got None

**Comment by petergridge** [comment]
That is odd, are there any errors in the log?

**Comment by petergridge** [comment]
The selector should only provide valid sensors. This is a long shot, can you:-
- Delete the instance from devices and services and check that all the sensors have been removed. 
- Remove the HACS repository
- Reinstall V2024.10.03 from HACS
- Set up again ( a good opportunity to try the auto-generated sensors :)

**Comment by Saschman** [comment]
Hi @petergridge ,

that seemed to do the trick.

It's working now.

Still one question...why are the update intervals of the different entities so different? 

Please see my screenshot:
<img width="449" alt="Bildschirmfoto 2024-10-09 um 11 10 26" src="https://github.com/user-attachments/assets/71d2eb1d-657b-4d71-877f-eca68f70a7ae">
