### ISSUE TITLE
Update for sensor.rainfactor fails

### ISSUE THREAD

**Issue by froggy974** [petergridge/openweathermaphistory#5]
hi,

since some days i have the following error message : 

````
Update for sensor.rainfactor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 518, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_device_update
    await task
  File "/config/custom_components/openweathermaphistory/sensor.py", line 235, in async_update
    await self._weatherhist.async_update()
  File "/config/custom_components/openweathermaphistory/weatherhistory.py", line 41, in async_update
    data = json.loads(rest.data)
  File "/usr/local/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
````

my config is the following 

```yaml
   sensor:
      - platform: openweathermaphistory
        name: 'rainfactor'
        api_key: !secret openweatherapi
```

openweather seems to be ok
![image](https://user-images.githubusercontent.com/17068466/153553509-e0494377-ac70-4942-bdb8-c2812848aae9.png)

is someone else have the same issue ?

**Comment by petergridge** [comment]
Hi Froggy, I'm not experiencing an issue with my instance. It appears the call to the weather service is not returning.

It uses 
https://api.openweathermap.org/data/2.5/onecall/timemachine?lat=66&lon=66&dt=1644966442&appid=yourapikey

1644966442 is the unix time you may need to change this, just use the current unix time from https://www.unixtimestamp.com/. 
Put your api key in and copy the link into your browser. 
You can replace the latitude and longitude data with your location if you want.

I know this is the old gem but you can also try restarting HA.

**Comment by froggy974** [comment]
i really dont understand why it's not working
the api call https://api.openweathermap.org/data/2.5/onecall/timemachine?lat=66&lon=66&dt=1644966442&appid=yourapikey is returning some data but `sensor.rainfactor` always stay at 1 despite the rain .

i gave up on opeaweather and i used a more basic rainsensor based on [meteo_france](https://www.home-assistant.io/integrations/meteo_france) integration

**Comment by alex4988** [comment]
i have same issue, how to resolve?
