### ISSUE TITLE
Peter, could you tell me how many of the free 500 api calls this will use a day?

### ISSUE THREAD

**Issue by wtstreetglow** [petergridge/openweathermaphistory#6]
Peter,

Hoping you could shed some light on the subject. I am using home assistant with the standard openweather integration and it is my understanding with default settings that, that integration uses 336 calls. How may calls does this use a day and is there anyway for the user to easily modify that?

**Comment by petergridge** [comment]
Hi, The default scan interval is 30 minutes, so it will use a relatively small number of calls, 48, I have the weather and history running together with no issues.

**Comment by wtstreetglow** [comment]
Thats great!! Thank you for responding. Also, I have one last question that I noticed earlier today. The documentations seems to say there will be history 5 days of rain and 5 days of min/max temps. (They seem to be numbered 0-4). However, in the attached screenshot, the integration brings in rain days of 0 to 5. Can you help me understand this? I have attached a screenshot of my states developer tab for the integration. Thank you again for responding and helping. I am new to HA, moving over from Smartthings.

![Untitled3](https://user-images.githubusercontent.com/30456018/175170622-edb26729-ab52-4714-9486-2cbe78f0e484.png)

**Comment by wtstreetglow** [comment]
Here is the discussion on the HA Forum if you would rather close all of this and talk over there. Thank you Peter!!

https://community.home-assistant.io/t/hoping-to-get-a-little-help-on-getting-today-rainfall-yesterday-rainfall-and-past-48h-rainfall-into-a-sensor-in-my-home-assistant-instance/433117/11
