### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by ColinRobbins** [petergridge/openweathermaphistory#9]
There seems to be a problem with the units calculations.
The docmentation says the default is `metric`, but the default seems to come back as imperial.
My HASS is congiured with metric as default.

The documetation says the units can be set via `unit_system`, but this results in HASS not loading the integartion, with an invalid intgration.

As I test,I tired changing line https://github.com/petergridge/openweathermaphistory/blob/b53108dfcd20b21b495db7bd08c1c72c5166871c/custom_components/openweathermaphistory/sensor.py#L95 from `imperial` to `metric`, the rain seem to come through as MM, but the temperature still in Farenheight.

**Comment by petergridge** [comment]
Thanks Colin, I will have a look into it, in my last update I removed the units option and used the HA units as the driver, this was  for rainfall, I did not look at temperature. I will investigate and get an update out.

**Comment by rjbungay** [comment]
Hi Peter
I found the same issue with the update to HA when they changed the way it handled the unit systems. 
I found your unit system check was failing at the "metric" test do setting "imperial" in two places in your code. 
I just hacked the file as below as I couldn't work out the correct fix for the "metric" test but I'm sure you will be able to. 

    units   = hass.config.units
    if units != 'metric':
        # units = 'imperial'
        units = 'metric'

Regards Richard

**Comment by rjbungay** [comment]
Currently my Rainfactor has become unavailable as well since the last HA update. Not had a chance to look into why this might be yet though.
